# Generated by Django 4.2 on 2023-08-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_probegcars_pc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='CarDetail',
        ),
    ]
