# Generated by Django 4.2 on 2023-08-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_auto_cardetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetail',
            new_name='Avto',
        ),
    ]
