# Generated by Django 4.2 on 2023-08-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cardetail_avto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProbegCars',
            new_name='Cars',
        ),
        migrations.DeleteModel(
            name='BusCars',
        ),
        migrations.DeleteModel(
            name='CommericalCars',
        ),
        migrations.DeleteModel(
            name='SmallCars',
        ),
        migrations.DeleteModel(
            name='Svp',
        ),
        migrations.DeleteModel(
            name='TruckCars',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='p_title',
            new_name='myname',
        ),
    ]
