# Generated by Django 4.2 on 2023-08-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_probegcars_cars_delete_buscars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avto',
            name='avto_year',
        ),
        migrations.RemoveField(
            model_name='avto',
            name='clas',
        ),
        migrations.RemoveField(
            model_name='avto',
            name='name',
        ),
        migrations.AddField(
            model_name='cars',
            name='massa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='mesta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='rasxod',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='size',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='tranmissiya',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Auto_Class',
        ),
        migrations.DeleteModel(
            name='Avto',
        ),
    ]
